version: "3.9"
services:
  solicitudes:
    build:
      context: .
      dockerfile: build/Dockerfile
    depends_on:
      - solicitudes-mongo
    ports:
      - "40401:40401"
    networks:
      - my_network
  solicitudes-mongo:
    image: mongo:4.4.18
    ports:
      - "40402:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - solicitudes-mongodata:/data/db
    networks:
      - my_network

volumes:
  solicitudes-mongodata:

networks:
  my_network:
    name: my_network
    external: true
